---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: workshoprootpassword
          - name: MYSQL_DATABASE
            value: workshopdb
          - name: MYSQL_USER
            value: workshopdb_user
          - name: MYSQL_PASSWORD
            value: workshoppassword123
        ports:
        - containerPort: 3306