---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql-service
          - name: WORDPRESS_DB_NAME
            value: workshopdb
          - name: WORDPRESS_DB_USER
            value: workshopdb_user
          - name: WORDPRESS_DB_PASSWORD
            value: workshoppassword123
        ports:
        - containerPort: 80